# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('reading', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='WordTranslations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=100)),
                ('word_type', models.CharField(max_length=10)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.Word')),
            ],
        ),
    ]
