# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_auto_20171212_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='alterreading',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='word',
            name='alterword',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='word',
            name='reading',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='wordtl',
            name='word_type',
            field=models.CharField(default='', max_length=80),
        ),
    ]
