# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0004_auto_20171212_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(default='', max_length=60),
        ),
    ]
