# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0006_auto_20171212_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordtl',
            name='word',
            field=models.ForeignKey(max_length=80, on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='dict.Word'),
        ),
    ]
