# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0007_auto_20171212_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordtl',
            name='word_type',
            field=models.CharField(default='', max_length=240),
        ),
    ]
