# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0008_auto_20171212_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordtl',
            name='translation',
            field=models.CharField(default='', max_length=500),
        ),
    ]
